name: Zig C++ MacOS ARM64
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest
    env:
      CC: zig cc -target riscv64-linux-musl
      CXX: zig c++ -target riscv64-linux-musl

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install cmake git wget xz
        git submodule update --init --recursive --depth=1
        # Install Zig
        wget https://ziglang.org/download/0.14.1/zig-aarch64-macos-0.14.1.tar.xz
        tar -xf zig-aarch64-macos-0.14.1.tar.xz

    - name: Build all examples
      working-directory: ${{github.workspace}}
      run: |
        export PATH=$PWD/zig-aarch64-macos-0.14.1:$PATH
        cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSTRIPPED=ON -DCMAKE_TOOLCHAIN_FILE=cmake/zig-toolchain.cmake
        cmake --build build --parallel 8
